apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: gcr.io/natural-furnace-461617-e0/auth
      context: apps/api/auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    # - image: gcr.io/natural-furnace-461617-e0/client
    #   context: apps/web
    #   sync:
    #     infer:
    #       - "**/*.ts"
    #       - "**/*.tsx"
    #       - "**/*.css"
    #   docker:
    #     dockerfile: Dockerfile
  googleCloudBuild:
    projectId: natural-furnace-461617-e0
  # local:
  #   push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
