apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: gcr.io/<your project id>/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/<your project id>/posts
      context: posts
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/<your project id>/apply
      context: apply
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/<your project id>/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/<your project id>/client
      context: client
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: <your project id>
manifests:
  rawYaml:
    - ./infra/k8s-gcp/k8s/*
    - ./infra/k8s-gcp/k8s-dev/*
deploy:
  kubectl: {}
